package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestConfig'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestConfig")) {
    check(maxRunningBuilds == 0) {
        "Unexpected option value: maxRunningBuilds = $maxRunningBuilds"
    }
    maxRunningBuilds = 1

    expectSteps {
        script {
            name = "Setup"
            executionMode = BuildStep.ExecutionMode.RUN_ON_SUCCESS
            scriptContent = """
                set -eu
                
                echo "%env.ROLE%"
            """.trimIndent()
        }
    }
    steps {
        insert(1) {
            dockerCommand {
                commandType = build {
                    source = file {
                        path = "Dockerfile"
                    }
                    contextDir = "."
                    commandArgs = """
                        --pull
                        --build-arg VAR="With Quotes"
                    """.trimIndent()
                }
            }
        }
    }
}
